ALTER SESSION SET CONSTRAINTS = DEFERRED;

DELETE FROM POSTS;
DELETE FROM THREADS;
DELETE FROM CATEGORIES;

INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Tecnología', 'Discusiones sobre las últimas tendencias tecnológicas, gadgets y software.');
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Videojuegos', 'Conversaciones sobre videojuegos, hardware de gaming y cultura gamer.');
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Películas y TV', 'Discusiones sobre películas, series de televisión, actores y la industria del entretenimiento.');
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Música', 'Comparte tus opiniones sobre música, artistas, álbumes y conciertos.');
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION) VALUES (CATEGORY_SEQ.NEXTVAL, 'Ciencia', 'Explora el mundo de la ciencia, desde la física hasta la biología y todo lo demás.');

INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) 
VALUES (THREAD_SEQ.NEXTVAL, 'El Futuro de la Inteligencia Artificial', SYSTIMESTAMP, SYSTIMESTAMP, 1, 1);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) 
VALUES (THREAD_SEQ.NEXTVAL, 'Mejores Lenguajes de Programación para Aprender en 2023', SYSTIMESTAMP, SYSTIMESTAMP, 2, 1);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) 
VALUES (THREAD_SEQ.NEXTVAL, 'Tendencias en Computación en la Nube', SYSTIMESTAMP, SYSTIMESTAMP, 3, 1);

INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) 
VALUES (THREAD_SEQ.NEXTVAL, 'Comparación de Consolas de Nueva Generación', SYSTIMESTAMP, SYSTIMESTAMP, 4, 2);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) 
VALUES (THREAD_SEQ.NEXTVAL, 'Mejores Juegos Indie de Todos los Tiempos', SYSTIMESTAMP, SYSTIMESTAMP, 5, 2);

INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) 
VALUES (THREAD_SEQ.NEXTVAL, 'Mejores Finales de Series de TV', SYSTIMESTAMP, SYSTIMESTAMP, 6, 3);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) 
VALUES (THREAD_SEQ.NEXTVAL, 'Próximas Películas de Marvel', SYSTIMESTAMP, SYSTIMESTAMP, 7, 3);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) 
VALUES (THREAD_SEQ.NEXTVAL, 'Películas Clásicas que Todos Deberían Ver', SYSTIMESTAMP, SYSTIMESTAMP, 8, 3);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) 
VALUES (THREAD_SEQ.NEXTVAL, 'Recomendaciones de Documentales', SYSTIMESTAMP, SYSTIMESTAMP, 9, 3);

INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) 
VALUES (THREAD_SEQ.NEXTVAL, 'Candidatos a Álbum del Año', SYSTIMESTAMP, SYSTIMESTAMP, 10, 4);

INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) 
VALUES (THREAD_SEQ.NEXTVAL, 'Últimos Descubrimientos en Astronomía', SYSTIMESTAMP, SYSTIMESTAMP, 11, 5);
INSERT INTO THREADS (ID, TITLE, CREATED_AT, LAST_UPDATED_AT, USER_ID, CATEGORY_ID) 
VALUES (THREAD_SEQ.NEXTVAL, 'Investigación sobre el Cambio Climático', SYSTIMESTAMP, SYSTIMESTAMP, 12, 5);

INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Creo que la IA revolucionará la atención médica en la próxima década.', SYSTIMESTAMP, SYSTIMESTAMP, 1, 1);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'También hay serias preocupaciones éticas que debemos abordar sobre el avance de la IA.', SYSTIMESTAMP, SYSTIMESTAMP, 2, 1);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'La IA ya está cambiando la forma en que trabajamos con herramientas como ChatGPT.', SYSTIMESTAMP, SYSTIMESTAMP, 3, 1);

INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Python sigue dominando debido a su simplicidad y versatilidad.', SYSTIMESTAMP, SYSTIMESTAMP, 4, 2);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Rust está ganando popularidad para aplicaciones críticas de rendimiento.', SYSTIMESTAMP, SYSTIMESTAMP, 5, 2);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'JavaScript es esencial para el desarrollo web y sigue evolucionando.', SYSTIMESTAMP, SYSTIMESTAMP, 6, 2);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Go es excelente para aplicaciones nativas en la nube.', SYSTIMESTAMP, SYSTIMESTAMP, 7, 2);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Kotlin se ha convertido en el lenguaje preferido para el desarrollo de Android.', SYSTIMESTAMP, SYSTIMESTAMP, 8, 2);

INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'La computación sin servidor está volviéndose cada vez más popular.', SYSTIMESTAMP, SYSTIMESTAMP, 9, 3);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Las estrategias de múltiples nubes son ahora estándar para grandes empresas.', SYSTIMESTAMP, SYSTIMESTAMP, 10, 3);

INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'La PS5 tiene mejores exclusivas, pero Xbox Game Pass ofrece un valor increíble.', SYSTIMESTAMP, SYSTIMESTAMP, 11, 4);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Todavía no puedo encontrar fácilmente una PS5 en las tiendas.', SYSTIMESTAMP, SYSTIMESTAMP, 12, 4);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Nintendo Switch sigue siendo la mejor opción portátil.', SYSTIMESTAMP, SYSTIMESTAMP, 1, 4);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Los juegos de PC son superiores si tienes el presupuesto para ello.', SYSTIMESTAMP, SYSTIMESTAMP, 2, 4);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Las guerras de consolas son inútiles. Simplemente disfruta jugando en la plataforma que prefieras.', SYSTIMESTAMP, SYSTIMESTAMP, 3, 4);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Estoy emocionado por la Steam Deck como nuevo competidor en el espacio.', SYSTIMESTAMP, SYSTIMESTAMP, 4, 4);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'El juego en la nube podría hacer que las consolas queden obsoletas eventualmente.', SYSTIMESTAMP, SYSTIMESTAMP, 5, 4);

INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Hollow Knight es mi juego indie favorito de todos los tiempos.', SYSTIMESTAMP, SYSTIMESTAMP, 6, 5);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Stardew Valley muestra cómo un desarrollador dedicado puede crear magia.', SYSTIMESTAMP, SYSTIMESTAMP, 7, 5);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Hades mereció todos los premios que ganó.', SYSTIMESTAMP, SYSTIMESTAMP, 8, 5);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Undertale revolucionó la narrativa en los juegos.', SYSTIMESTAMP, SYSTIMESTAMP, 9, 5);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Los juegos indie a menudo toman más riesgos creativos que los títulos AAA.', SYSTIMESTAMP, SYSTIMESTAMP, 10, 5);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Celeste no es solo un gran juego, sino que también tiene un mensaje importante.', SYSTIMESTAMP, SYSTIMESTAMP, 11, 5);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Among Us mostró cómo los juegos indie pueden volverse virales de repente.', SYSTIMESTAMP, SYSTIMESTAMP, 12, 5);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Disco Elysium tiene la mejor escritura que he visto en un juego.', SYSTIMESTAMP, SYSTIMESTAMP, 1, 5);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Las bandas sonoras de juegos indie suelen ser fenomenales.', SYSTIMESTAMP, SYSTIMESTAMP, 2, 5);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'La escena indie es donde ocurre la mayor innovación en los videojuegos.', SYSTIMESTAMP, SYSTIMESTAMP, 3, 5);

INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Breaking Bad tuvo el final perfecto.', SYSTIMESTAMP, SYSTIMESTAMP, 4, 6);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Todavía no puedo superar lo malo que fue el final de Juego de Tronos.', SYSTIMESTAMP, SYSTIMESTAMP, 5, 6);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'El final de The Good Place me hizo llorar, pero de buena manera.', SYSTIMESTAMP, SYSTIMESTAMP, 6, 6);

INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Creo que Marvel podría estar teniendo problemas de fatiga de superhéroes últimamente.', SYSTIMESTAMP, SYSTIMESTAMP, 7, 7);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'La historia del multiverso está abriendo tantas posibilidades.', SYSTIMESTAMP, SYSTIMESTAMP, 8, 7);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Estoy emocionado porque los X-Men finalmente se unan al MCU.', SYSTIMESTAMP, SYSTIMESTAMP, 9, 7);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Black Panther: Wakanda Forever fue un hermoso tributo a Chadwick Boseman.', SYSTIMESTAMP, SYSTIMESTAMP, 10, 7);

INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'El Padrino sigue siendo la mejor película jamás hecha.', SYSTIMESTAMP, SYSTIMESTAMP, 11, 8);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, '12 Hombres en Pugna muestra que no necesitas un gran presupuesto para hacer una obra maestra.', SYSTIMESTAMP, SYSTIMESTAMP, 12, 8);

INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Planeta Tierra II es visualmente impresionante.', SYSTIMESTAMP, SYSTIMESTAMP, 1, 9);

INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, '¿Qué álbumes creen que merecen el Álbum del Año?', SYSTIMESTAMP, SYSTIMESTAMP, 2, 10);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Creo que SOS de SZA debería ganar este año.', SYSTIMESTAMP, SYSTIMESTAMP, 3, 10);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Renaissance de Beyoncé fue revolucionario.', SYSTIMESTAMP, SYSTIMESTAMP, 4, 10);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Los Grammy rara vez aciertan de todos modos.', SYSTIMESTAMP, SYSTIMESTAMP, 5, 10);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Los artistas independientes merecen más reconocimiento en las categorías principales de premios.', SYSTIMESTAMP, SYSTIMESTAMP, 6, 10);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Extraño la era de los álbumes - ahora todo se trata de singles y reproducciones.', SYSTIMESTAMP, SYSTIMESTAMP, 7, 10);

INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Las imágenes del Telescopio Espacial James Webb son impresionantes.', SYSTIMESTAMP, SYSTIMESTAMP, 8, 11);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'El descubrimiento de más exoplanetas potencialmente habitables es muy emocionante.', SYSTIMESTAMP, SYSTIMESTAMP, 9, 11);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'La imagen de agujeros negros es uno de los logros más significativos en la astronomía moderna.', SYSTIMESTAMP, SYSTIMESTAMP, 10, 11);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Nuestra comprensión de la materia oscura está evolucionando constantemente.', SYSTIMESTAMP, SYSTIMESTAMP, 11, 11);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Los astrónomos aficionados continúan haciendo contribuciones importantes al campo.', SYSTIMESTAMP, SYSTIMESTAMP, 12, 11);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Me asombran los recientes descubrimientos sobre las lunas de Júpiter.', SYSTIMESTAMP, SYSTIMESTAMP, 1, 11);

INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'El último informe del IPCC es preocupante pero también ofrece vías para la acción.', SYSTIMESTAMP, SYSTIMESTAMP, 2, 12);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'La adopción de energías renovables se está acelerando, lo que me da esperanza.', SYSTIMESTAMP, SYSTIMESTAMP, 3, 12);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'La acidificación de los océanos no recibe suficiente atención en las discusiones sobre el clima.', SYSTIMESTAMP, SYSTIMESTAMP, 4, 12);
INSERT INTO POSTS (ID, CONTENT, CREATED_AT, LAST_UPDATED_AT, USER_ID, THREAD_ID) 
VALUES (POST_SEQ.NEXTVAL, 'Las nuevas tecnologías de captura de carbono muestran prometedores avances.', SYSTIMESTAMP, SYSTIMESTAMP, 5, 12);

ALTER SESSION SET CONSTRAINTS = IMMEDIATE; 